// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1LinpJy2pI5jLlrfELGWQ2Zuat-oqSs',
    appId: '1:977105515482:web:cad333d7301d6c26ca46e3',
    messagingSenderId: '977105515482',
    projectId: 'smartroute-f8df3',
    authDomain: 'smartroute-f8df3.firebaseapp.com',
    storageBucket: 'smartroute-f8df3.firebasestorage.app',
    measurementId: 'G-JWG3CMNQLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQQZdDX7ndnH2DUeD56X3FAChFT5ny9c',
    appId: '1:977105515482:android:fb13df85136ad082ca46e3',
    messagingSenderId: '977105515482',
    projectId: 'smartroute-f8df3',
    storageBucket: 'smartroute-f8df3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw68_eVMNbAax08gh2AW6iD1Ruwg-wl98',
    appId: '1:977105515482:ios:b7c7d009ddb343aaca46e3',
    messagingSenderId: '977105515482',
    projectId: 'smartroute-f8df3',
    storageBucket: 'smartroute-f8df3.firebasestorage.app',
    iosBundleId: 'com.example.user',
  );
}
