import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/models/address_model.dart';
import '../../../../core/services/firestore_service.dart';
import '../../../auth/presentation/notifiers/auth_notifier.dart';

class AddressState {
  final List<AddressModel> addresses;
  final bool isLoading;

  AddressState({
    this.addresses = const [],
    this.isLoading = false,
  });

  AddressState copyWith({
    List<AddressModel>? addresses,
    bool? isLoading,
  }) {
    return AddressState(
      addresses: addresses ?? this.addresses,
      isLoading: isLoading ?? this.isLoading,
    );
  }
}

final addressNotifierProvider = StateNotifierProvider<AddressNotifier, AddressState>((ref) {
  final authState = ref.watch(authNotifierProvider);
  return AddressNotifier(ref.read(firestoreServiceProvider), authState);
});

class AddressNotifier extends StateNotifier<AddressState> {
  final FirestoreService _firestoreService;
  final AuthState _authState;

  AddressNotifier(this._firestoreService, this._authState) : super(AddressState()) {
    _listenToAddresses();
  }

  void _listenToAddresses() {
    if (_authState.user == null) return;
    
    _firestoreService.streamAddresses(_authState.user!.uid).listen((addressesData) {
      final models = addressesData.map((data) => AddressModel.fromJson(data)).toList();
      state = state.copyWith(addresses: models);
    });
  }

  Future<void> addAddress({
    required String label,
    required String address,
    String? city,
    String? stateRegion,
    String? postalCode,
  }) async {
    if (_authState.user == null) return;
    
    state = state.copyWith(isLoading: true);
    try {
      final newAddress = AddressModel(
        id: '', // Will be generated by Firestore
        label: label,
        address: address,
        city: city,
        state: stateRegion,
        postalCode: postalCode,
        latitude: 0.0, // Mock coordinates
        longitude: 0.0,
      );
      
      final String uid = _authState.user!.uid;
      await _firestoreService.saveAddress(uid, newAddress.toJson());
      state = state.copyWith(isLoading: false);
    } catch (e) {
      state = state.copyWith(isLoading: false);
    }
  }

  Future<void> deleteAddress(String addressId) async {
    // Implementation for deletion if needed
  }
}
