import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/models/payment_method_model.dart';
import '../../../../core/services/firestore_service.dart';
import '../../../auth/presentation/notifiers/auth_notifier.dart';

class PaymentState {
  final List<PaymentMethodModel> cards;
  final bool isLoading;

  PaymentState({
    this.cards = const [],
    this.isLoading = false,
  });

  PaymentState copyWith({
    List<PaymentMethodModel>? cards,
    bool? isLoading,
  }) {
    return PaymentState(
      cards: cards ?? this.cards,
      isLoading: isLoading ?? this.isLoading,
    );
  }
}

final paymentNotifierProvider = StateNotifierProvider<PaymentNotifier, PaymentState>((ref) {
  final authState = ref.watch(authNotifierProvider);
  return PaymentNotifier(ref.read(firestoreServiceProvider), authState);
});

class PaymentNotifier extends StateNotifier<PaymentState> {
  final FirestoreService _firestoreService;
  final AuthState _authState;

  PaymentNotifier(this._firestoreService, this._authState) : super(PaymentState()) {
    _listenToPaymentMethods();
  }

  void _listenToPaymentMethods() {
    if (_authState.user == null) return;
    
    _firestoreService.streamPaymentMethods(_authState.user!.uid).listen((cardsData) {
      final models = cardsData.map((data) => PaymentMethodModel.fromJson(data)).toList();
      state = state.copyWith(cards: models);
    });
  }

  Future<void> addCard(String cardNumber, String expiryDate, String cardType) async {
    if (_authState.user == null) return;
    
    state = state.copyWith(isLoading: true);
    try {
      // Obfuscate card number: **** **** **** 1234
      final last4 = cardNumber.substring(cardNumber.length - 4);
      final obfuscated = '**** **** **** $last4';
      
      final newCard = PaymentMethodModel(
        id: '', // Will be generated by Firestore
        cardNumber: obfuscated,
        expiryDate: expiryDate,
        cardType: cardType,
      );
      
      await _firestoreService.savePaymentMethod(_authState.user!.uid, newCard.toJson());
      state = state.copyWith(isLoading: false);
    } catch (e) {
      state = state.copyWith(isLoading: false);
    }
  }
}
